### ISSUE TITLE
Segment photos of bookshelves using CV

### ISSUE THREAD

**Issue by dingchaoz** [dingchaoz/bookshelf#6]
An approach to be experimented:

- Convert images to grayscale:
```gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)```
- Canny edge detector to detect edges: https://docs.opencv.org/trunk/da/d22/tutorial_py_canny.html
- Straight line detection using Hough transform:
https://www.geeksforgeeks.org/line-detection-python-opencv-houghline-method/
- Segment and extract each book using straight lines
- Run through the segmented photos to Google API to extract text

**Comment by dingchaoz** [comment]
latest update, book spine detection is completed: https://github.com/dingchaoz/bookshelf/blob/high_res_image/notebooks/detect_lines.ipynb.
Next steps:
- Remove close lines by considering line length comparison and line-to-line distance
- Segment book out 
- Run through Google API to extract text

**Comment by shhudspeth** [comment]
I've completed removing extraneous lines and created bounding boxes. I planned to do a mask in OpenCv for the bounding boxes, but since most of the notebook is not in openCV I'm not sure what the best approach is and if I should use some other masking functions. I'll go ahead and add masking functions in the notebook as well as a call to google and see if that works!

**Comment by shhudspeth** [comment]
Completed the following:
-Remove close lines by considering line length comparison and line-to-line distance
-Segment book out
-Run through Google API to extract text

I'm going to add an issue for the next steps!
